//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemProjectWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class BookingTable
    {
        public int Booking_id { get; set; }

        [Required(ErrorMessage = "UserEmail Is Required")]
        public string User_Email { get; set; }
        [Required(ErrorMessage = "Date Of Funtion Is Required")]
        public System.DateTime Date_Of_Function { get; set; }
        [Required(ErrorMessage = "Type Of Function Is Required")]
        public string Type_Of_Function { get; set; }
        [Required(ErrorMessage = "Function Menue Is Required")]
        public string Function_Menue { get; set; }
        [Required(ErrorMessage = "Number Of Guests required")]
        public int No_Of_Guests { get; set; }
        [Required(ErrorMessage = "Vehicle Parking Space required")]
        public int Vehicle_Parking_Space { get; set; }
    }
}
